DjangoBlog/DjangoBlog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from crypto.views import get_crypto

urlpatterns = [
    url(r'', include("blog.urls")),
    url(r'^crypto/', include("crypto.urls")),
    url(r'^admin/', admin.site.urls),
]

DjangoBlog/blog/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView

from blog import views

app_name = 'blog'

urlpatterns = [
    #url(r'^$', views.home, name="home"),
    #url(r'^$', views.HomeView.as_view(), name="home"),
    url(r'^$', views.PostListView.as_view(), name="home"),
    url(r'^post/',views.post,name='new_post'),
    url(r'post_detail/(?P<pk>\d+)', views.PostDetailView.as_view(), name='detail'),
    # url(r'^about/', views.about, name="about"),
    url(r'^about/', TemplateView.as_view(template_name='about.html'), name="about"),
    #url(r'^contact/', views.contact, name="contact"),
    url(r'^contact/', views.ContactView.as_view(), name="contact"),
    url(r'^account/',include("django.contrib.auth.urls"), name="login"),
    url(r'^search/',views.search, name="search"),

]

DjangoBlog/crypto/urls.py
from django.conf.urls import url


from crypto.views import get_crypto

urlpatterns = [
    url(r'^coin/', get_crypto, name="crypto"),
]

DjangoBlog/blog/models.py
from django.db import models
from django.db.models import CASCADE
from django.utils import timezone


# Our cusotm model managers
class PublishManager(models.Manager):
    def get_queryset(self):
        return super(PublishManager, self).get_queryset()\
                                          .filter(status='published')\
                                          .order_by('-created')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    title = models.CharField(max_length=250)
    author = models.ForeignKey("auth.User", related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    # managers
    objects = models.Manager()
    published = PublishManager() # use our custom model manager

    # Meta information
    class Meta:
        ordering = ('-publish',) # sort by publish date in the admin view

    # String representation
    def __str__(self):
        return self.title


class Comment(models.Model):
    post_id = models.ForeignKey('Post', related_name='post_comments', on_delete=CASCADE)
    name = models.CharField(max_length=20)
    email = models.EmailField(blank=True, null=True)
    comment_body = models.TextField(max_length=200)

    def __str__(self):
        return "{} in ({})".format(self.name,self.post_id.title)

DjangoBlog/crypto/models.py
from django.db import models

# Create your models here.

DjangoBlog/blog/forms.py
from django.forms import forms,ModelForm
from blog.models import Comment, Post


class CommentForm(ModelForm):
     class Meta:
         model=Comment
         fields=['name','email','comment_body']


class PostForm(ModelForm):
    class Meta:
        model=Post
        fields=['title','author','body','status']

DjangoBlog/blog/views.py
from itertools import count

from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import TemplateView, ListView, DetailView

from blog.forms import CommentForm, PostForm
from blog.models import Post, Comment


# def home(request):
#     object_list = Post.objects.order_by("-created_date")
#     count = object_list.count()
#     ctx = {
#         "object_list": object_list,
#         "count": count
#     }
#     return render(request, 'home.html', context=ctx)


def get_one_post(request, *args, **kwargs):
    arg = kwargs.get('pk')
    # one_post = Post.objects.get(pk=arg)
    one_post = get_object_or_404(Post, pk=arg)
    ctx = {
        "one_post": one_post
    }
    return render(request, 'blog/post_detail.html', context=ctx)


# def about(request):
#     return render(request, 'about.html', context={})

# def contact(request):
#     return render(request, 'contact.html', context={})


class HomeView(TemplateView):
    def get(self, request, *args, **kwargs):
        object_list = Post.objects.order_by("-created")
        count = object_list.count()
        ctx = {
            "object_list": object_list,
            "count": count,
        }
        return render(request, 'blog/home.html', context=ctx)


class ContactView(TemplateView):
    def get(self, request, *args, **kwargs):
        return render(request, 'contact.html', context={})


class PostListView(ListView):
    model = Post
    template_name = 'blog/home.html'

    # Option 1
    #  queryset = Post.objects.filter(status='published').order_by('-created')

    # Option 2
    # def get_queryset(self):
    #     return Post.objects.order_by('-created_date')

    # Option 3
    def get_context_data(self, **kwargs):
        context = super(PostListView, self).get_context_data(**kwargs)
        # context['object_list'] = Post.objects.order_by('-created')
        # context['object_list'] = Post.objects.filter(status='published').order_by('-created')
        context['object_list'] = Post.published.all()
        context['count'] = context['object_list'].count()
        return context


class PostDetailView(DetailView):
    # Old method
    # model = Post
    # context_object_name = 'one_post'
    # template_name = 'blog/post_detail.html'

    # def get_context_data(self, **kwargs):
    #     context = super(PostDetailView, self).get_context_data(**kwargs)
    #     context['comments'] = Comment.objects.all()
    #     return context

    # New method: To get post and the comments
    def get(self, request, *args, **kwargs):
        pk = kwargs.get('pk')

        # get one object
        one_post = Post.objects.get(pk=pk)

        # based on the object, get the comments in the post
        # comments = Comment.objects.filter(post_id=one_post)
        comments = one_post.post_comments.all()
        comment_form = CommentForm()

        # Prepare context
        ctx = {
            "one_post": one_post,
            'comments': comments,
            "comment_form": comment_form
        }
        return render(request, 'blog/post_detail.html', context=ctx)

    def post(self, request, *args, **kwargs):
        comments = CommentForm(data=request.POST)
        if comments.is_valid():
            new_comment = comments.save(commit=False)
            post_comment = get_object_or_404(Post, pk=kwargs.get('pk'))
            new_comment.post_id = post_comment
            new_comment.save()
            return redirect('blog:detail', pk=post_comment.pk)


def post(request):
    post_list = PostForm()
    ctx = {
        'post_list': post_list
    }
    if request.method == 'POST':
        com = PostForm(data=request.POST)
        com.save()
        return redirect('blog:home')
    else:
        pass
    return render(request, template_name='blog/new_post.html', context=ctx)




def search(request, *args, **kwargs):
    query = request.POST.get('searchquery')
    result = Post.objects.filter(Q(title__contains=query) | Q(body__contains=query)).filter(status="published")
    count = result.count()

    ctx = {
        'result': result,
        'count': count
    }
    return render(request, 'blog/searchresult.html', context=ctx)


@login_required
def new_post(request):
    if request.method == "POST":
        new_post_form = PostForm(request.POST)
        if new_post_form.is_valid():
            post = new_post_form.save(commit=False)
            post.author = request.user
            post.save()
            redirect('blog:post_detail', pk=new_post_form.pk)
    else:
        form = PostForm()
        return render(request, 'blog/new_post.html', {'form': form})

DjangoBlog/crypto/views.py
from django.shortcuts import render

import requests

API = "https://api.coinmarketcap.com/v1/ticker/?limit=10"

def get_crypto(request):
    data = requests.get(API).json()
    ctx = {
        "data": data
    }
    return render(request, 'templates/crypto/crypto_currency.html', context=ctx)

DjangoBlog/blog/templates/blog/home.html
<h1>Welcome to everyone </h1>
{% extends 'base.html' %}
{% load pagination_tags %}

{% block bodyBlock %}
    {% autopaginate object_list 2 %}
{#    {{ object_list|length }} post entries are found.#}
    {{ count }} post entries are found.
    <hr>
    {% for object in object_list %}
        <div class="post">
{#            <h3>{{ forloop.counter }} <a href="{% url 'detail' pk=object.pk %}">{{ object.title|cut:" " }}</a></h3>#}
            <h3><a href="{% url 'blog:detail' pk=object.pk %}">{{ object.title }}</a></h3>
            <small>{{ object.created|date:"Y M d D" }} {{ object.created|time:"h:i" }}</small>
{#            <p>{{ object.content|truncatechars:"10" }}</p>#}
            <p>{{ object.body|truncatewords:3 }}</p>
        </div>
    {% empty %}
        <p>No entries found</p>
    {% endfor %}
    <div>
    {% paginate %}
    </div>
{% endblock %}

DjangoBlog/blog/templates/blog/new_post.html
{% extends 'base.html' %}

{% block bodyBlock %}
<form action="" method="post" class="form-horizontal">
    {% csrf_token%}
    {{ post_list.as_p }}
    <input type="submit" class="btn btn-success" value="Add Post">
</form>
{% endblock %}

DjangoBlog/blog/templates/blog/post.html
{% extends 'base.html' %}
{% block bodyBlock %}
<form action="" method="post">
{% csrf_token %}
{{ post_list }}
    <input type="submit" class="btn btn-success" value="Add Post">
    </form>
{% endblock %}

DjangoBlog/blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% block bodyBlock %}

    <h2>{{ one_post.title }}</h2>
    <small>Post By: {{ one_post.author }} in {{ one_post.created }}</small>
    <p>{{ one_post.body }}</p>

    <h3>Comments:</h3>

    {% for comment in comments %}
        <hr>
        <p>{{ comment.name }}</p>
        <br>
        <p>{{ comment.comment_body }}</p>
    {% empty %}
        <p>No comments yet</p>
    {% endfor %}
    <form action="" method="post">
        {% csrf_token %}
        {{ comment_form.as_p }}
    <input type="submit" class="btn btn-success" value="Add Comment">

    </form>

{% endblock bodyBlock %}

DjangoBlog/blog/templates/blog/searchresult.html
{% extends 'base.html' %}
{% block bodyBlock %}
    <ul>

            {% for res in result %}
                <p>
                 <a href="{% url 'blog:detail' pk=res.pk %}">{{ res }}</a></p>
            {% empty %}
            <p>No results found</p>
            {% endfor %}
    </ul>
    {{ count }} related posts found

{% endblock bodyBlock %}

DjangoBlog/crypto/templates/crypto/crypto_currency.html
{% extends 'base.html' %}

{% block bodyBlock %}

    <table class="table table-bordered table-stripped table-hover table-sm">
        <thead>
        <tr>
            <th>Rank</th>
            <th>Name</th>
            <th>Price in USD</th>
            <th>Symbol</th>
        </tr>
        </thead>

        <tbody>
        {% for each in data %}
            <tr class="
                {% if each.percent_change_24h.0 == "-" %}
                    text-danger
                {% else %}
                    text-success
            {% endif %}">
                <td>{{ each.rank }}</td>
                <td>{{ each.name }}</td>
                <td>$ {{ each.price_usd }}</td>
                <td>{{ each.symbol }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock bodyBlock %}

DjangoBlog/templates/about.html
{% extends 'base.html' %}

{% block bodyBlock %}
    <h1>This is about page from TemplateView</h1>
{% endblock %}

DjangoBlog/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>www.blog.com</title>
    {% include 'snippets/css.html' %}
    {% include 'snippets/js.html' %}
</head>
<body>
{% include 'snippets/nav.html' %}

{#<img src="{% static 'tys.jpg' %}" alt="alt text" width="200px" height="200px">#}

<div class="container">
    <div class="row">
        <div class="col-8">
            {% block bodyBlock %}

            {% endblock bodyBlock %}
        </div>
    </div>
</div>



</body>
</html>

DjangoBlog/templates/contact.html
{% extends 'base.html' %}

{% block bodyBlock %}
    <h1>This is contact page</h1>
{% endblock %}

DjangoBlog/templates/contactus.html
{%  extends 'base.html' %}

{% block bodyBlog %}
    <h1>
    this is contactus page
    </h1>
{% endblock %}

DjangoBlog/templates/crypto_currency.html
{% extends 'base.html' %}
{% block bodyBlog %}

    <table class="table table-bordered table-stripped table-hover table-sm">
        <thead align="center">
        <tr>
            <th>Rank</th>
            <th>Name</th>
            <th>Price</th>
            <th>Symbol</th>
        </tr>
        </thead>

        <tbody align="center">
        {% for each in data %}
            <tr class="{% if each.percent_change_24h.0 == "-" %} text-danger
            {% else %}text-success

            {% endif %}">
                <td>{{ each.rank }}</td>
                <td>{{ each.name }}</td>
                <td>${{ each.price_usd }}</td>
                <td>{{ each.symbol }}</td>

            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock bodyBlog %}

DjangoBlog/templates/home.html
{%  extends 'base.html' %}
{% block bodyBlog %}
    <div class="col-sp-4">
        <h1>This is homepage </h1>
    <h1>{{ co }} entries found</h1>
        {% for each in object %}
            <h2>{{ each.title }}</h2>
            <small>{{ each.created_date }}</small>
            <p>{{ each.content | truncatechars:"5" }}</p>

            {%   empty %}
            <h1>No content to display</h1>

        {% endfor %}
    </div>

{% endblock %}

DjangoBlog/templates/snippets/css.html
{% load staticfiles %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'styles.css' %}">

DjangoBlog/templates/snippets/js.html
{% load staticfiles %}

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<script src="{% static 'app.js' %}"></script>

DjangoBlog/templates/snippets/nav.html
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'blog:home' %}">My Blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'blog:home' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:about' %}">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:contact' %}">Contact</a>
                    </li>

                    <li class="nav-item">

                    </li>

                    <li class="nav-item">
                        {% if  user.is_authenticated %}
                            <a class="nav-link" href="{% url 'blog:new_post' %}">Add Post</a></li>

                            <small>Logged in as:{{ user.username }}</small>
                            <a class="nav-link" href="{% url 'blog:logout' %}?next={{request.path}}">Logout</a>
                        {% else %}
                            <a class="nav-link" href="{% url 'blog:login' %}?next={{request.path}}">Login</a>
                        {% endif %}
                    </li>

                </ul>
                <form class="form-inline" method="post" action="{% url 'blog:search' %}">
                    {% csrf_token %}

                    <input class="form-control mr-sm-2" type="search" placeholder="Search"name="searchquery" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>